### ISSUE TITLE
Failing to install on KDE Neon 

### ISSUE THREAD

**Issue by merzainc** [moodyhunter/applet-window-buttons6#5]
![btns](https://github.com/moodyhunter/applet-window-buttons6/assets/114744793/7dce1ce4-edf4-40f9-89e6-28118e496bfe)

**Comment by moodyhunter** [comment]
You seem to have KF6 beta installed, while I would suggest installing the released final version instead, but you can revert https://github.com/moodyhunter/applet-window-buttons6/commit/1b2a472019daf05d6826aaf24217ccd3fd00122b manually to resolve the issue.

**Comment by merzainc** [comment]
> You seem to have KF6 beta installed, while I would suggest installing the released final version instead, you can revert [1b2a472](https://github.com/moodyhunter/applet-window-buttons6/commit/1b2a472019daf05d6826aaf24217ccd3fd00122b) manually to resolve the issue.

I did revert manually to [1b2a472](https://github.com/moodyhunter/applet-window-buttons6/commit/1b2a472019daf05d6826aaf24217ccd3fd00122b) to resolve the issue but the error is persisting. How can to install KF6 final version instead of the beta?

**Comment by moodyhunter** [comment]
Ooops sorry I misread your error output, can you ensure that you have `KDeclarative` and `KSvg` installed?

**Comment by merzainc** [comment]
> Ooops sorry I misread your error output, can you ensure that you have `KDeclarative` and `KSvg` installed? The package is probably named `libkf6declarative-dev`

`KDeclarative` issues is now fixed, thank you but now getting an error associated with `KSvg`. 
Here is the error log: 
![error](https://github.com/moodyhunter/applet-window-buttons6/assets/114744793/21fb3542-e7b8-47d2-9b15-83c5c9944a9e)

Thank you for helping me so far, i want `applet-window-appmenu` and `applet-window-buttons` so that i can restore my previous setup.

**Comment by merzainc** [comment]
> > Ooops sorry I misread your error output, can you ensure that you have `KDeclarative` and `KSvg` installed? The package is probably named `libkf6declarative-dev`
> 
> `KDeclarative` issues is now fixed, thank you but now getting an error associated with `KSvg`. Here is the error log: ![error](https://private-user-images.githubusercontent.com/114744793/311520331-21fb3542-e7b8-47d2-9b15-83c5c9944a9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwODQwNzQsIm5iZiI6MTcxMDA4Mzc3NCwicGF0aCI6Ii8xMTQ3NDQ3OTMvMzExNTIwMzMxLTIxZmIzNTQyLWU3YjgtNDdkMi05YjE1LTgzYzVjOTk0NGE5ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMFQxNTE2MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYTdlYTg0MmIwNDU2OGI5MGIzZjg1ZmEyYzk4OTlkNDkyMjU1MDhiODNlZDYxM2ZiNWNhYzA2NjU4MDNjZGEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MpUDyXrA2pX9NIKz4RuUOnHaYzGYQOdljMhNTsjgqMI)
> 
> Thank you for helping me so far, i want `applet-window-appmenu` and `applet-window-buttons` so that i can restore my previous setup.

Managed to successfully install the applet, i had to install a set of packages to achieve success. List of packages inlcude `libkf6declarative-dev`, `libkf6kcmutils-dev`, `libkf6configwidgets-dev`,`libkf6service-dev` and `libkf6svg-dev`. 

Closing this issue. Hope it will work as expected.

**Comment by EulogioIV** [comment]
Hello @merzainc, it seems that the only `libkf6svg-dev` not found in my system:
![image](https://github.com/moodyhunter/applet-window-buttons6/assets/122346629/605c7530-e775-487f-8be1-171cd1967339)

I'm using a fresh installed of KDE Neon so i'm wondering if I missed something.

**Comment by merzainc** [comment]
> Hello @merzainc, it seems that the only `libkf6svg-dev` package is missing/not found in my system:
> 
> ![image](https://private-user-images.githubusercontent.com/122346629/313378989-605c7530-e775-487f-8be1-171cd1967339.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2NDAyODcsIm5iZiI6MTcxMDYzOTk4NywicGF0aCI6Ii8xMjIzNDY2MjkvMzEzMzc4OTg5LTYwNWM3NTMwLWU3NzUtNDg3Zi04YmUxLTE3MWNkMTk2NzMzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxN1QwMTQ2MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYmM0MTZmNjllMGJkYmZhZDQ0MWMyMzBhYzBjNThhNmFjZjY0NTVjNTk3Y2Y1MzVmNmZlZjYwMmM2NDgzZWFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gJgCk7enN-XFcT-2VVp8fxf7ByfRcxXmtOUtnNYufZI)
> 
> I'm using a fresh installed of KDE Neon so i'm wondering if I missed something. Can you help me with this specific package?
> 
> **UPDATE:** I managed to make it work, instead of `libkf6svg-dev`, install this `kf6-ksvg-dev` instead

Hy champion unfortunately i uninstalled Neon but I'm sure it was a mistake. You're ✅️
